services:
  users-ms:
    build: ./lib-app/users-ms
    container_name: users-ms
    volumes:
      - ./lib-app/users-ms:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      - NATS_SERVERS=nats://nats:4222
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users-example
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - nats
      - postgres
    networks:
      - app-network

  auth-ms:
    build: ./lib-app/auth-ms
    container_name: auth-ms
    volumes:
      - ./lib-app/auth-ms:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3002:3002"
    environment:
      - NATS_SERVERS=nats://nats:4222
    depends_on:
      - nats
    networks:
      - app-network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users-example
      - POSTGRES_USER=postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge